version: "3.8"
services:
    database:
        container_name: Database-Server
        image: postgres
        networks:
            - network
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
networks:
    network:
        driver: bridge
